/** AUTO-GENERATED by JCEF TypeScriptObjectProcessor – DO NOT EDIT **/
import { CefQueryService } from '../../jcef/CefQueryService';

export class RandomQueryHandler {
    public static simpleQuery(query: string): Promise<number> {
        return CefQueryService.request('example.RandomQueryHandler', 'simpleQuery', {query}, 'number');
    }

}
