/** AUTO-GENERATED by JCEF TypeScriptObjectProcessor – DO NOT EDIT **/
import { CefCommunicationService } from '../../jcef/CefCommunicationService';

export class RandomQueryHandler {
    public static simpleQuery(query: string): Promise<number> {
        return CefCommunicationService.request('example.RandomQueryHandler', 'simpleQuery', {query}, 'number');
    }

}
