/** AUTO-GENERATED by JCEF TypeScriptObjectProcessor – DO NOT EDIT **/
import { CefRestService } from '../../jcef/CefRestService';

export class RandomQueryHandler {
    public static simpleQuery(query: string): Promise<number> {
        return CefRestService.request('example.RandomQueryHandler', 'simpleQuery', {query}, 'number');
    }

}
